#!/usr/bin/env node
/**
 * Icons: copy the icon library's sprite into the app and write the list of
 * names the <Icon> component accepts.
 *
 *   design/assets/icons/sprite.svg      (source, hand-drawn; never regenerated)
 *   → public/assets/icons/sprite.svg    (served at /assets/icons/sprite.svg)
 *   → src/generated/icons.ts            (IconName, and name → symbol id)
 *
 * Companion marks are left out: they are character art, and the crew's
 * painted portraits replace them in the interface.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const uiDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const lib = resolve(uiDir, "..", "design/assets/icons");
const manifest = JSON.parse(readFileSync(resolve(lib, "manifest.json"), "utf-8"));
const sprite = readFileSync(resolve(lib, "sprite.svg"), "utf-8");

const icons = manifest.icons
  .filter((i) => i.category !== "companion")
  .map((i) => ({ name: i.name, id: `icon-${i.category}-${i.name}` }))
  .sort((a, b) => (a.name < b.name ? -1 : 1));

for (const { id } of icons) {
  if (!sprite.includes(`id="${id}"`)) {
    console.error(`✗ manifest names ${id} but the sprite has no such symbol`);
    process.exit(1);
  }
}

mkdirSync(resolve(uiDir, "public/assets/icons"), { recursive: true });
writeFileSync(resolve(uiDir, "public/assets/icons/sprite.svg"), sprite);

const ts = `// Generated by scripts/generate-icons.mjs from design/assets/icons. Do not edit.
export const ICON_IDS = {
${icons.map((i) => `  ${JSON.stringify(i.name)}: ${JSON.stringify(i.id)},`).join("\n")}
} as const;

export type IconName = keyof typeof ICON_IDS;
`;
writeFileSync(resolve(uiDir, "src/generated/icons.ts"), ts);
console.log(`✓ ${icons.length} icons → public/assets/icons/sprite.svg, src/generated/icons.ts`);
